### PR TITLE
ADD GitHub action for infracost

### PR DESCRIPTION
**Pull request by davidjeddy**

### CODE REVIEW

**Review by boril82 — COMMENTED** [review]
approved by a noob

**Review by boril82 — COMMENTED** [review]
approved by a noob

**Review by boril82 — COMMENTED** [review]
approved by a noob

**Review by boril82 — COMMENTED** [review]
approved

**Comment by davidjeddy** [comment]
@boril82 did you click the approve button?

**Review by boril82 — APPROVED** [review]

**Comment by boril82** [comment]
@davidjeddy I did now, I was mistakenly making just comments

**Pull request merged**
